services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: servia_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./ServIA_BACKEND
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:1234@db:5432/servia_db
      SECRET_KEY: "_Av13cu#7-LfUNXa+xMUz6Y"
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./Front-ServiceIA
    environment:
      EXPO_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: